# Generated by Django 5.2 on 2025-06-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_person_hidden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['id']},
        ),
    ]
